src/FtpPlayground.Mvc/Models/Explorer/ExplorerFtpDetailsModel.cs
using System.Runtime.Serialization;

namespace FtpPlayground.Mvc.Models
{
    [DataContract]
    public class ExplorerFtpDetailsModel
    {
        [DataMember(Order = 1)]
        public string FtpUri { get; set; }

        [DataMember(Order = 2)]
        public string FtpUsername { get; set; }

        [DataMember(Order = 3)]
        public string FtpPassword { get; set; }
    }
}

src/FtpPlayground.Mvc/Models/Explorer/ExplorerGridItem.cs
using System;
using System.Runtime.Serialization;

namespace FtpPlayground.Mvc.Models
{
    [DataContract]
    public class ExplorerGridItem
    {
        /// <summary>
        /// Sequential id of the item.
        /// </summary>
        [DataMember(Order = 1)]
        public int Id { get; set; }

        /// <summary>
        /// Name of file or directory.
        /// </summary>
        [DataMember(Order = 2)]
        public string FileName { get; set; }

        /// <summary>
        /// True if current item appears to be a directory link otherwise False.
        /// </summary>
        [DataMember(Order = 3)]
        public bool IsDirectory { get; set; }

        /// <summary>
        /// Download id of the item.
        /// </summary>
        [DataMember(Order = 4)]
        public Guid? DownloadId { get; set; }
    }
}

src/FtpPlayground.Mvc/Models/Explorer/ExplorerModel.cs
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace FtpPlayground.Mvc.Models
{
    /// <summary>
    /// Model for Explorer page.
    /// </summary>
    /// <remarks>
    /// In order to store this model in cache we need to decorate all model members with attributes that will be used by the chosen serialization framework.
    /// </remarks>
    [DataContract]
    public class ExplorerModel
    {
        [DataMember(Order = 1)]
        public List<ExplorerGridItem> GridItems { get; set; }
    }
}

src/FtpPlayground.Mvc/Controllers/ExplorerController.cs
using FtpPlayground.Caching;
using FtpPlayground.DownloadManager;
using FtpPlayground.Logging;
using FtpPlayground.Mvc.Models;
using FtpPlayground.Mvc.Utilities;
using FtpPlayground.Serialization;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Unity.Attributes;

namespace FtpPlayground.Mvc.Controllers
{
    public class ExplorerController : AbstractController
    {
        /// <summary>
        /// Key used to store model in the cache.
        /// </summary>
        private readonly string _sessionCacheKeyModel;

        /// <summary>
        /// Key used to store FTP details in the cache.
        /// </summary>
        private readonly string _sessionCacheKeyFtpModel;

        /// <summary>
        /// Manager class used for downloading files in the background.
        /// </summary>
        private IDownloadManager _downloadManager;

        /// <summary>
        /// SignalR hub client used to send notification messages to the browser.
        /// </summary>
        private IDownloadManagerHubClient _downloadManagerHubClient;

        public ExplorerController(
            ILoggerFactory loggerFactory,
            ICacheClientFactory cacheClientFactory,
            ISerializer serializer)
            : base(loggerFactory, cacheClientFactory, serializer)
        {
            // TODO: 
            // Move key initialization logic into Initialize() method and add user information to it.
            // This will allow us to store sessions per user rather than share one among all users. 
            _sessionCacheKeyModel = $"session-model-{nameof(ExplorerController)}";
            _sessionCacheKeyFtpModel = $"session-ftp-{nameof(ExplorerController)}";
        }

        /// <summary>
        /// We use an injection method for some dependecies which are not used across all controllers. This helps keep our <see cref="AbstractController"/> constructor a bit cleaner.
        /// </summary>
        /// <param name="downloadManager"></param>
        [InjectionMethod]
        public void InjectionMethod(
            IDownloadManager downloadManager,
            IDownloadManagerHubClient downloadManagerHubClient)
        {
            if (downloadManager == null)
            {
                throw new ArgumentNullException(nameof(downloadManager));
            }

            if (downloadManagerHubClient == null)
            {
                throw new ArgumentNullException(nameof(downloadManagerHubClient));
            }

            _downloadManager = downloadManager;
            _downloadManagerHubClient = downloadManagerHubClient;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<ActionResult> LoadGrid(string ftpUri, string ftpUsername, string ftpPassword)
        {
            // Validate parameters
            if (string.IsNullOrWhiteSpace(ftpUri))
            {
                throw new ArgumentNullException(nameof(ftpUri));
            }

            if (string.IsNullOrWhiteSpace(ftpUsername))
            {
                throw new ArgumentNullException(nameof(ftpUsername));
            }

            if (string.IsNullOrWhiteSpace(ftpPassword))
            {
                throw new ArgumentNullException(nameof(ftpPassword));
            }

            try
            {
                var ftpDirectoryListing = "";

                #region >>>> Fetch data from FTP server

                // Note: This call will throw if the uri we passed in is invalid or not absolute,
                // doing it like this simplifies our error checks and keeps the flow a little cleaner.
                var requestUri = new Uri(ftpUri, UriKind.Absolute);

                // Init request
                var request = WebRequest.Create(ftpUri) as FtpWebRequest;
                request.Credentials = new NetworkCredential(ftpUsername, ftpPassword);

                // Set the command we want to execute on the ftp server. In this case we are interested in the directory listing.
                request.Method = WebRequestMethods.Ftp.ListDirectory;

                // Query server using an asynchronous call to get the response
                using (var response = await request.GetResponseAsync() as FtpWebResponse)
                {
                    // Check response
                    if (response == null)
                    {
                        throw new InvalidOperationException($"FTP server response is null.");
                    }

                    if (!(response.StatusCode == FtpStatusCode.OpeningData ||
                        response.StatusCode == FtpStatusCode.ClosingData))
                    {
                        throw new InvalidOperationException($"FTP server response does not indicate success. Message: {response.StatusDescription}");
                    }

                    // Process response stream                    
                    using (var stream = response.GetResponseStream())
                    {
                        using (var reader = new StreamReader(stream))
                        {
                            ftpDirectoryListing = await reader.ReadToEndAsync();
                        }
                    }
                }
                #endregion

                #region >>>> Init models

                var ftpModel = new ExplorerFtpDetailsModel
                {
                    FtpUri = ftpUri,
                    FtpUsername = ftpUsername,
                    FtpPassword = ftpPassword,
                };

                var model = new ExplorerModel
                {
                    GridItems = new List<ExplorerGridItem> { }
                };

                // Check response body we got from the ftp server and fill our model
                if (!string.IsNullOrWhiteSpace(ftpDirectoryListing))
                {
                    // Response body contains directory listing separated by carriage returns. So we need to 
                    // split it into individual lines.
                    var ftpDirectoryItems = ftpDirectoryListing.Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);

                    if (ftpDirectoryItems.Length > 0)
                    {
                        var itemId = 1;

                        model.GridItems = ftpDirectoryItems
                            .Select(x =>
                            {
                                var item = new ExplorerGridItem
                                {
                                    Id = itemId,
                                    FileName = x,

                                    // Note: Here we try to guess if the file name returned by the server is in fact a directory link.                                     
                                    IsDirectory = !x.Contains("."),
                                };

                                itemId++;

                                return item;
                            })
                            .OrderByDescending(x => x.IsDirectory)
                            .ToList();
                    }
                }

                #endregion

                #region >>>> Store models in cache

                // Note: 
                // Before we can store our models in cache we have to serialize it. Here we use our serialization abstraction to 
                // do just that.
                // Advantage of doing it this way is that our application is generally oblivious to the underlying serialization protocol that
                // we decide to use. Should we change it in the future there will be no need to change the code.
                CacheClient.AddOrSet(_sessionCacheKeyModel, Serializer.Serialize(model));
                CacheClient.AddOrSet(_sessionCacheKeyFtpModel, Serializer.Serialize(ftpModel));

                #endregion

                // Render our view and return the result
                if (Request.IsAjaxRequest())
                {
                    return PartialView("_Grid", model);
                }

                return View(model);
            }
            catch (Exception ex)
            {
                // Log
                Logger.Error($"{nameof(ExplorerController.LoadGrid)}: Could not load grid.", ex);

                // Re-throw the exception so it can get handled via the MVC pipeline
                throw;
            }
        }

        [HttpGet]
        public ActionResult DownloadFile(int fileId)
        {
            try
            {
                #region >>>> Load models from cache

                // Note:
                // Usually we would wrap this logic in a convinient generic extension method and avoid the pain of having to write everything
                // out like this. 

                var modelBuffer = CacheClient.Get(_sessionCacheKeyModel);

                if (modelBuffer == null)
                {
                    throw new InvalidOperationException($"Could not load {nameof(ExplorerModel)} from cache.");
                }

                var model = Serializer.Deserialize<ExplorerModel>(modelBuffer);

                if (model == null)
                {
                    throw new InvalidOperationException($"Could not deserialize {nameof(ExplorerModel)}.");
                }

                var ftpModelBuffer = CacheClient.Get(_sessionCacheKeyFtpModel);

                if (ftpModelBuffer == null)
                {
                    throw new InvalidOperationException($"Could not load {nameof(ExplorerFtpDetailsModel)} from cache.");
                }

                var ftpModel = Serializer.Deserialize<ExplorerFtpDetailsModel>(ftpModelBuffer);

                if (ftpModel == null)
                {

src/FtpPlayground.Mvc/Views/Explorer/Index.cshtml
<div class="row">
    <h2>Explorer</h2>
    <p>This page lets you browse contents of an FTP server.</p>
</div>

<div class="row">

    <!-- FTP server details -->
    <div class="col-lg-3 col-md-6" style="padding-right:10px">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">FTP Server Details</h3>
            </div>
            <div class="panel-body fixed-panel">
                <form class="form-horizontal" style="padding-left:20px; padding-right:20px">
                    <div class="form-group">
                        <!-- Textbox: FTP Uri -->
                        <div class="input-group">
                            <span id="label-explorer-ftp-uri" class="input-group-addon"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span></span>
                            <input id="txt-explorer-ftp-uri" type="text" class="form-control" placeholder="FTP server address" aria-describedby="label-explorer-ftp-uri" value="ftp://ftp.otenet.gr/ubuntu" /><!-- ftp://test.rebex.net/pub/example ftp://ftp.dlptest.com/-->
                        </div>
                    </div>
                    <div class="form-group">
                        <!-- Textbox: Username -->
                        <div class="input-group">
                            <span id="label-explorer-ftp-username" class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                            <input id="txt-explorer-ftp-username" type="text" class="form-control" placeholder="Username" aria-describedby="label-explorer-ftp-username" value="anonymous" /> <!-- demo dlpuser@dlptest.com-->
                        </div>
                    </div>
                    <div class="form-group">
                        <!-- Textbox: Password -->
                        <div class="input-group">
                            <span id="label-explorer-ftp-password" class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                            <input id="txt-explorer-ftp-password" type="password" class="form-control" placeholder="Password" aria-describedby="txt-explorer-ftp-password" value="anonymous" /> <!-- password e73jzTRTNqCN9PYAAjjn-->
                        </div>
                    </div>
                    <div class="form-group">
                        <!-- Button: Fetch -->
                        <div class="input-group col-md-3">
                            <button id="btn-explorer-fetch" type="button" class="btn btn-primary ld-ext-right">Fetch<div class="ld ld-ring ld-spin"></div></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Grid -->
    <div class="col-lg-9 col-md-6">
        <div id="container-explorer-grid" class="panel panel-default ld-over">
            <div class="ld ld-ring ld-spin" style="font-size:2em"></div>
            <div class="panel-heading">
                <h3 class="panel-title">Directory Listing</h3>
            </div>
            <div class="panel-body fixed-panel-scroll">
                <div id="container-explorer-griditems" style="padding-left:20px; padding-right:20px">
                    @{Html.RenderPartial("_Grid");}
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    // Get references to commonly used controls
    var btnExplorerFetch = $('#btn-explorer-fetch');
    var txtExplorerFtpUri = $('#txt-explorer-ftp-uri');
    var txtExplorerFtpUsername = $('#txt-explorer-ftp-username');
    var txtExplorerFtpPassword = $('#txt-explorer-ftp-password');

    var containerExplorerGrid = $('#container-explorer-grid');
    var containerExplorerGridItems = $('#container-explorer-griditems');

    // Init
    $(document).ready(function () {

        // Disable caching of AJAX responses
        $.ajaxSetup({
            cache: false
        });

        // Event handlers
        btnExplorerFetch.on('click', function () {

            // TODO: Parameter validation

            // Get current ftp parameters and load the grid
            loadGrid(
                txtExplorerFtpUri.val(),
                txtExplorerFtpUsername.val(),
                txtExplorerFtpPassword.val()
            );
        });

    });

    // Loads grid items from server
    function loadGrid(ftpUri, ftpUsername, ftpPassword) {

        // Block UI elements
        blockUI();

        // Init request
        var requestData = {
            ftpUri: ftpUri,
            ftpUsername: ftpUsername,
            ftpPassword: ftpPassword,
        };

        // Send async ajax request
        $.ajax({
            type: 'GET',
            url: '@Url.Action("LoadGrid", "Explorer")',
            data: requestData,
            async: true,
            success: function (res) {

                // Render partial view
                containerExplorerGridItems.html(res);

                // Unblock UI elements
                unblockUI();

            },
            error: function (result, status, er) {
                // TODO: Remove
                // alert('error: ' + result + ' status: ' + status + ' er:' + er);
            },
            complete: function () {
                // Unblock UI elements
                unblockUI();
            }
        });
    }

    // Downloads file from server
    function downloadFile(fileId, okCallback, errorCallback) {

        // Init request
        var requestData = {
            fileId: fileId
        };

        // Send async ajax request
        $.ajax({
            type: 'GET',
            url: '@Url.Action("DownloadFile", "Explorer")',
            data: requestData,
            async: true,
            success: function (res) {
                okCallback(res);
            },
            error: function (result, status, er) {
                // debugger;
                errorCallback(fileId);
            },
            complete: function () {
                // debugger;
            }
        });
    }

    // Blocks buttons and grid container
    function blockUI() {

        // Block controls if they are not blocked
        if (!btnExplorerFetch.hasClass('running')) {
            btnExplorerFetch.addClass('running');
            btnExplorerFetch.prop("disabled", true);
        }

        if (!containerExplorerGrid.hasClass('running')) {
            containerExplorerGrid.addClass('running');
            containerExplorerGrid.prop("disabled", true);
        }
    }

    // Unblocks buttons and grid container
    function unblockUI() {

        // Block controls if they are blocked
        if (btnExplorerFetch.hasClass('running')) {
            btnExplorerFetch.removeClass('running');
            btnExplorerFetch.prop("disabled", false);
        }

        if (containerExplorerGrid.hasClass('running')) {
            containerExplorerGrid.removeClass('running');
            containerExplorerGrid.prop("disabled", false);
        }
    }

</script>

src/FtpPlayground.Mvc/Views/Explorer/_Grid.cshtml
@model FtpPlayground.Mvc.Models.ExplorerModel

<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th style="width:10%">Type</th>
                <th style="width:40%">File / Directory Name</th>
                <th style="width:40%"></th>
                <th style="width:10%">Action</th>
            </tr>
        </thead>
        <tbody>
            @{
                if (Model != null && Model.GridItems != null)
                {
                    foreach (var item in Model.GridItems)
                    {
                        <tr>
                            @if (item.IsDirectory)
                            {
                                <!-- Directory -->
                                <td scope="row">
                                    <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
                                </td>
                                <td>@item.FileName</td>
                                <td></td>
                                <td><button id="btn-open-folder" type="button" class="btn btn-default btn-block btn-xs" data-directoryid="@item.Id" disabled>Open</button></td>
                            }
                            else
                            {
                                <!-- File -->
                                <td scope="row">
                                    <span class="glyphicon glyphicon-file" aria-hidden="true"></span>
                                </td>
                                <td>@item.FileName</td>
                                <td>
                                    <div class="progress invisible" style="height: 1px; margin-top:5px; margin-bottom:0;">
                                        <div id="bar-download-progress-@item.Id" class="progress-bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                    <p id="txt-download-status-@item.Id" class="text-muted text-right" style="font-size:10px"></p>
                                </td>
                                <td><button id="btn-download-file" type="button" class="btn btn-success btn-block btn-xs" data-fileid="@item.Id">Download <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span></button></td>
                            }
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>

<script type="text/javascript">

    $(document).ready(function () {

        // Grid items event handlers
        var downloadFileButtons = $('button[id="btn-download-file"]');

        if (downloadFileButtons.length > 0) {

            downloadFileButtons.on('click', function (e) {

                // Get file id of the file we want to download
                var fileId = $(e.currentTarget).data('fileid');

                downloadFile(fileId,
                    // Ok
                    function (res) {
                        // debugger;

                        var downloadStatusElement = $('#txt-download-status-' + fileId);
                        var downloadProgressElement = $('#bar-download-progress-' + fileId);

                        // Add download id data attribute to the grid item
                        downloadStatusElement.attr("data-downloadId", res.downloadId);
                        downloadProgressElement.attr("data-downloadId", res.downloadId);
                    },
                    // Error
                    function (fileId) {
                        // debugger;
                    });
            });
        }

        // TODO
        //var openFolderButtons = $('button[id="btn-open-folder"]');

        //if (openFolderButtons) {
        //    openFolderButtons.on('click', function (e) {
        //    });
        //}

        // SignalR event handlers
        downloadManagerHubProxy.on('downloadProgress', function (downloadId, downloadRate, downloadSize, downloadProgress, downloadTime) {
            $('[id*="txt-download-status"][data-downloadId="' + downloadId + '"]').text(downloadRate + ' - ' + downloadSize + ', ' + downloadTime);

            $('[id*="bar-download-progress"][data-downloadId="' + downloadId + '"]').parent().removeClass('invisible');
            $('[id*="bar-download-progress"][data-downloadId="' + downloadId + '"]').css('width', downloadProgress + '%');
        });

        downloadManagerHubProxy.on('downloadCompleted', function (downloadId, downloadTime, filePath, error) {
            $('[id*="txt-download-status"][data-downloadId="' + downloadId + '"]').text(filePath + ' Completed in ' + downloadTime);
            $('[id*="bar-download-progress"][data-downloadId="' + downloadId + '"]').css('width', '100%');
        });

        downloadManagerHubProxy.on('downloadCancelled', function (downloadId, filePath) {
            $('[id*="txt-download-status"][data-downloadId="' + downloadId + '"]').text(filePath + ' Cancelled');
            $('[id*="bar-download-progress"][data-downloadId="' + downloadId + '"]').css('width', '0%');
        });

    });

</script>